// the 'Database' of badge infos
var badgeInfos = [
  {
    firstName : 'Imelda',
    lastName  : 'Udinesi',
    role      : 'developer',
    markerId  : 123,
    avatar    : 'avatar/avatars/avatar-123.png',
  },
  {
    firstName : 'Maria',
    lastName  : 'Piccio',
    role      : 'industry',
    markerId  : 256,
    avatar    : 'avatar/avatars/avatar-256.png',
  },
  {
    firstName : 'Alceo',
    lastName  : 'Cocci',
    role      : 'designer',
    markerId  : 265,
    avatar    : 'avatar/avatars/avatar-265.png',
  },
  {
    firstName : 'Consuelo',
    lastName  : 'Pugliesi',
    role      : 'other',
    markerId  : 318,
    avatar    : 'avatar/avatars/avatar-318.png',
  },
  {
    firstName : 'Antonietta',
    lastName  : 'Trentini',
    role      : 'industry',
    markerId  : 394,
    avatar    : 'avatar/avatars/avatar-394.png',
  },
  {
    firstName : 'Arnaldo',
    lastName  : 'Lucchese',
    role      : 'industry',
    markerId  : 401,
    avatar    : 'avatar/avatars/avatar-401.png',
  },
  {
    firstName : 'Noemi',
    lastName  : 'Lombardo',
    role      : 'other',
    markerId  : 423,
    avatar    : 'avatar/avatars/avatar-423.png',
  },
  {
    firstName : 'Palmiro',
    lastName  : 'Barese',
    role      : 'developer',
    markerId  : 523,
    avatar    : 'avatar/avatars/avatar-523.png',
  },
  {
    firstName : 'Innocenzo',
    lastName  : 'Dellucci',
    role      : 'other',
    markerId  : 641,
    avatar    : 'avatar/avatars/avatar-641.png',
  },
  {
    firstName : 'Biagio',
    lastName  : 'Loggia',
    role      : 'designer',
    markerId  : 781,
    avatar    : 'avatar/avatars/avatar-781.png',
  },
  {
    firstName : 'Simona',
    lastName  : 'Sagese',
    role      : 'developer',
    markerId  : 845,
    avatar    : 'avatar/avatars/avatar-845.png',
  },
  {
    firstName : 'Pancrazio',
    lastName  : 'Pisano',
    role      : 'designer',
    markerId  : 987,
    avatar    : 'avatar/avatars/avatar-987.png',
  },
]
